package com.ben.compiler.utils;
/**
 * @author @zhangchuan622@gmail.com
 * @version 1.0
 * @create 2017-08-03
 */
public class Consts {
    public static final String JAVADOC = "\rauto generate.do not edit this file! \rcreate on @zhangchuan622@gmail.com\n ";
    /**
     * 路由参数自动注入 后缀
     */
    public static final String PROXY_ROUTER_SUFFIX = "$$Proxy$$Router";

    public static final String ACTIVITY = "android.app.Activity";
    public static final String FRAGMENT = "android.app.Fragment";
    public static final String FRAGMENT_V4 = "android.support.v4.app.Fragment";
    public static final String PARCELABLE = "android.os.Parcelable";
    public static final String ROOT_PACKAGE_NAME = "com.ben";
    /**
     * 指定Autowrite类型注解被注册处理器注册
     */
    public static final String ANNOTATION_TYPE = ROOT_PACKAGE_NAME + ".annotations.annotation.Autowrite";
    public static final String PROXY_ROUTER_CLASS_NAME = ROOT_PACKAGE_NAME + ".api.router.proxy.IRouterProxy";
    public static final String PROXY_ROUTER_METHOD_NAME = "inject";

    // Java type
    private static final String LANG = "java.lang";
    private static final String UTIL = "java.util";
    public static final String BYTE = LANG + ".Byte";
    public static final String SHORT = LANG + ".Short";
    public static final String INTEGER = LANG + ".Integer";
    public static final String LONG = LANG + ".Long";
    public static final String FLOAT = LANG + ".Float";
    public static final String DOUBEL = LANG + ".Double";
    public static final String BOOLEAN = LANG + ".Boolean";
    public static final String STRING = LANG + ".String";
    public static final String ARRAYLIST = UTIL + ".ArrayList";
}